-- ref: http://www.h2database.com/html/datatypes.html

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID          IDENTITY      AUTO_INCREMENT  PRIMARY KEY,
  NAME        VARCHAR(255)  NOT NULL UNIQUE,
  GENDER      BOOLEAN       NOT NULL,
  SIGNATURE   VARCHAR(255)
);

INSERT INTO USER(NAME, GENDER, SIGNATURE) VALUES ('zhang1', true,  '');
INSERT INTO USER(NAME, GENDER, SIGNATURE) VALUES ('zhang2', false, '');
INSERT INTO USER(NAME, GENDER, SIGNATURE) VALUES ('zhang3', true,  '');
INSERT INTO USER(NAME, GENDER, SIGNATURE) VALUES ('li1', true,  '');
INSERT INTO USER(NAME, GENDER, SIGNATURE) VALUES ('li2', false, '');
INSERT INTO USER(NAME, GENDER, SIGNATURE) VALUES ('li3', true,  '');
