
# 错误处理相关
server.error.include-stacktrace: on_trace_param
#server.error.path: /error

# template 相关
#spring.thymeleaf.prefix: classpath:/templates/


spring.profiles.active: a1
security.basic.enabled: false
security.user.password: 123456

logging.level.org.springframework.web: INFO
logging.level.org.springframework.security: INFO
logging.level.org.springframework.boot.actuate.audit.listener.AuditListener: DEBUG
logging.level.org.springframework.boot.web.support.ErrorPageFilter: DEBUG
logging.level.org.springframework.web.servlet.view.ContentNegotiatingViewResolver: DEBUG
logging.level.org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping: DEBUG
# 用来追踪 restTemplate 请求
logging.level.org.apache.http: DEBUG

spring.devtools.restart.exclude: static/**,public/**,templates/**,resources/**


# JacksonProperties
spring.jackson.joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
spring.jackson.default-property-inclusion: non_null

