/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.records;


import com.github.btpka3.first.spring.jooq.domain.tables.ActorInfo;

import javax.annotation.processing.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActorInfoRecord extends TableRecordImpl<ActorInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.actor_info.actor_id</code>.
     */
    public void setActorId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.actor_info.actor_id</code>.
     */
    public Short getActorId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>sakila.actor_info.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.actor_info.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.actor_info.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.actor_info.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sakila.actor_info.film_info</code>.
     */
    public void setFilmInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.actor_info.film_info</code>.
     */
    public String getFilmInfo() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActorInfoRecord
     */
    public ActorInfoRecord() {
        super(ActorInfo.ACTOR_INFO);
    }

    /**
     * Create a detached, initialised ActorInfoRecord
     */
    public ActorInfoRecord(Short actorId, String firstName, String lastName, String filmInfo) {
        super(ActorInfo.ACTOR_INFO);

        setActorId(actorId);
        setFirstName(firstName);
        setLastName(lastName);
        setFilmInfo(filmInfo);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ActorInfoRecord
     */
    public ActorInfoRecord(com.github.btpka3.first.spring.jooq.domain.tables.pojos.ActorInfo value) {
        super(ActorInfo.ACTOR_INFO);

        if (value != null) {
            setActorId(value.getActorId());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setFilmInfo(value.getFilmInfo());
            resetTouchedOnNotNull();
        }
    }
}
