/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.records;


import com.github.btpka3.first.spring.jooq.domain.tables.FilmCategory;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilmCategoryRecord extends UpdatableRecordImpl<FilmCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.film_category.film_id</code>.
     */
    public void setFilmId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.film_category.film_id</code>.
     */
    public Short getFilmId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>sakila.film_category.category_id</code>.
     */
    public void setCategoryId(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.film_category.category_id</code>.
     */
    public Byte getCategoryId() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>sakila.film_category.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.film_category.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, Byte> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmCategoryRecord
     */
    public FilmCategoryRecord() {
        super(FilmCategory.FILM_CATEGORY);
    }

    /**
     * Create a detached, initialised FilmCategoryRecord
     */
    public FilmCategoryRecord(Short filmId, Byte categoryId, LocalDateTime lastUpdate) {
        super(FilmCategory.FILM_CATEGORY);

        setFilmId(filmId);
        setCategoryId(categoryId);
        setLastUpdate(lastUpdate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FilmCategoryRecord
     */
    public FilmCategoryRecord(com.github.btpka3.first.spring.jooq.domain.tables.pojos.FilmCategory value) {
        super(FilmCategory.FILM_CATEGORY);

        if (value != null) {
            setFilmId(value.getFilmId());
            setCategoryId(value.getCategoryId());
            setLastUpdate(value.getLastUpdate());
            resetTouchedOnNotNull();
        }
    }
}
