/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.records;


import com.github.btpka3.first.spring.jooq.domain.tables.FilmText;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilmTextRecord extends UpdatableRecordImpl<FilmTextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.film_text.film_id</code>.
     */
    public void setFilmId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.film_text.film_id</code>.
     */
    public Short getFilmId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>sakila.film_text.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.film_text.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sakila.film_text.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.film_text.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilmTextRecord
     */
    public FilmTextRecord() {
        super(FilmText.FILM_TEXT);
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(Short filmId, String title, String description) {
        super(FilmText.FILM_TEXT);

        setFilmId(filmId);
        setTitle(title);
        setDescription(description);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised FilmTextRecord
     */
    public FilmTextRecord(com.github.btpka3.first.spring.jooq.domain.tables.pojos.FilmText value) {
        super(FilmText.FILM_TEXT);

        if (value != null) {
            setFilmId(value.getFilmId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
            resetTouchedOnNotNull();
        }
    }
}
