/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.records;


import com.github.btpka3.first.spring.jooq.domain.tables.Inventory;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.inventory.inventory_id</code>.
     */
    public void setInventoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sakila.inventory.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sakila.inventory.film_id</code>.
     */
    public void setFilmId(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>sakila.inventory.film_id</code>.
     */
    public Short getFilmId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>sakila.inventory.store_id</code>.
     */
    public void setStoreId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>sakila.inventory.store_id</code>.
     */
    public Byte getStoreId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>sakila.inventory.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sakila.inventory.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(Integer inventoryId, Short filmId, Byte storeId, LocalDateTime lastUpdate) {
        super(Inventory.INVENTORY);

        setInventoryId(inventoryId);
        setFilmId(filmId);
        setStoreId(storeId);
        setLastUpdate(lastUpdate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(com.github.btpka3.first.spring.jooq.domain.tables.pojos.Inventory value) {
        super(Inventory.INVENTORY);

        if (value != null) {
            setInventoryId(value.getInventoryId());
            setFilmId(value.getFilmId());
            setStoreId(value.getStoreId());
            setLastUpdate(value.getLastUpdate());
            resetTouchedOnNotNull();
        }
    }
}
