/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.records;


import com.github.btpka3.first.spring.jooq.domain.tables.Payment;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> implements Record7<Short, Short, Byte, Integer, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.payment.payment_id</code>.
     */
    public PaymentRecord setPaymentId(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.payment_id</code>.
     */
    public Short getPaymentId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>sakila.payment.customer_id</code>.
     */
    public PaymentRecord setCustomerId(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.customer_id</code>.
     */
    public Short getCustomerId() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>sakila.payment.staff_id</code>.
     */
    public PaymentRecord setStaffId(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.staff_id</code>.
     */
    public Byte getStaffId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>sakila.payment.rental_id</code>.
     */
    public PaymentRecord setRentalId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.rental_id</code>.
     */
    public Integer getRentalId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sakila.payment.amount</code>.
     */
    public PaymentRecord setAmount(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>sakila.payment.payment_date</code>.
     */
    public PaymentRecord setPaymentDate(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.payment_date</code>.
     */
    public LocalDateTime getPaymentDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sakila.payment.last_update</code>.
     */
    public PaymentRecord setLastUpdate(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>sakila.payment.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Short, Short, Byte, Integer, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Short, Short, Byte, Integer, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Short> field1() {
        return Payment.PAYMENT.PAYMENT_ID;
    }

    @Override
    public Field<Short> field2() {
        return Payment.PAYMENT.CUSTOMER_ID;
    }

    @Override
    public Field<Byte> field3() {
        return Payment.PAYMENT.STAFF_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Payment.PAYMENT.RENTAL_ID;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Payment.PAYMENT.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Payment.PAYMENT.PAYMENT_DATE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Payment.PAYMENT.LAST_UPDATE;
    }

    @Override
    public Short component1() {
        return getPaymentId();
    }

    @Override
    public Short component2() {
        return getCustomerId();
    }

    @Override
    public Byte component3() {
        return getStaffId();
    }

    @Override
    public Integer component4() {
        return getRentalId();
    }

    @Override
    public BigDecimal component5() {
        return getAmount();
    }

    @Override
    public LocalDateTime component6() {
        return getPaymentDate();
    }

    @Override
    public LocalDateTime component7() {
        return getLastUpdate();
    }

    @Override
    public Short value1() {
        return getPaymentId();
    }

    @Override
    public Short value2() {
        return getCustomerId();
    }

    @Override
    public Byte value3() {
        return getStaffId();
    }

    @Override
    public Integer value4() {
        return getRentalId();
    }

    @Override
    public BigDecimal value5() {
        return getAmount();
    }

    @Override
    public LocalDateTime value6() {
        return getPaymentDate();
    }

    @Override
    public LocalDateTime value7() {
        return getLastUpdate();
    }

    @Override
    public PaymentRecord value1(Short value) {
        setPaymentId(value);
        return this;
    }

    @Override
    public PaymentRecord value2(Short value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public PaymentRecord value3(Byte value) {
        setStaffId(value);
        return this;
    }

    @Override
    public PaymentRecord value4(Integer value) {
        setRentalId(value);
        return this;
    }

    @Override
    public PaymentRecord value5(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public PaymentRecord value6(LocalDateTime value) {
        setPaymentDate(value);
        return this;
    }

    @Override
    public PaymentRecord value7(LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public PaymentRecord values(Short value1, Short value2, Byte value3, Integer value4, BigDecimal value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(Short paymentId, Short customerId, Byte staffId, Integer rentalId, BigDecimal amount, LocalDateTime paymentDate, LocalDateTime lastUpdate) {
        super(Payment.PAYMENT);

        setPaymentId(paymentId);
        setCustomerId(customerId);
        setStaffId(staffId);
        setRentalId(rentalId);
        setAmount(amount);
        setPaymentDate(paymentDate);
        setLastUpdate(lastUpdate);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(com.github.btpka3.first.spring.jooq.domain.tables.pojos.Payment value) {
        super(Payment.PAYMENT);

        if (value != null) {
            setPaymentId(value.getPaymentId());
            setCustomerId(value.getCustomerId());
            setStaffId(value.getStaffId());
            setRentalId(value.getRentalId());
            setAmount(value.getAmount());
            setPaymentDate(value.getPaymentDate());
            setLastUpdate(value.getLastUpdate());
        }
    }
}
