/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.records;


import com.github.btpka3.first.spring.jooq.domain.tables.Store;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StoreRecord extends UpdatableRecordImpl<StoreRecord> implements Record4<Byte, Byte, Short, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sakila.store.store_id</code>.
     */
    public StoreRecord setStoreId(Byte value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>sakila.store.store_id</code>.
     */
    public Byte getStoreId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>sakila.store.manager_staff_id</code>.
     */
    public StoreRecord setManagerStaffId(Byte value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>sakila.store.manager_staff_id</code>.
     */
    public Byte getManagerStaffId() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>sakila.store.address_id</code>.
     */
    public StoreRecord setAddressId(Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>sakila.store.address_id</code>.
     */
    public Short getAddressId() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>sakila.store.last_update</code>.
     */
    public StoreRecord setLastUpdate(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>sakila.store.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Byte, Byte, Short, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Byte, Byte, Short, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Byte> field1() {
        return Store.STORE.STORE_ID;
    }

    @Override
    public Field<Byte> field2() {
        return Store.STORE.MANAGER_STAFF_ID;
    }

    @Override
    public Field<Short> field3() {
        return Store.STORE.ADDRESS_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Store.STORE.LAST_UPDATE;
    }

    @Override
    public Byte component1() {
        return getStoreId();
    }

    @Override
    public Byte component2() {
        return getManagerStaffId();
    }

    @Override
    public Short component3() {
        return getAddressId();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdate();
    }

    @Override
    public Byte value1() {
        return getStoreId();
    }

    @Override
    public Byte value2() {
        return getManagerStaffId();
    }

    @Override
    public Short value3() {
        return getAddressId();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdate();
    }

    @Override
    public StoreRecord value1(Byte value) {
        setStoreId(value);
        return this;
    }

    @Override
    public StoreRecord value2(Byte value) {
        setManagerStaffId(value);
        return this;
    }

    @Override
    public StoreRecord value3(Short value) {
        setAddressId(value);
        return this;
    }

    @Override
    public StoreRecord value4(LocalDateTime value) {
        setLastUpdate(value);
        return this;
    }

    @Override
    public StoreRecord values(Byte value1, Byte value2, Short value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StoreRecord
     */
    public StoreRecord() {
        super(Store.STORE);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(Byte storeId, Byte managerStaffId, Short addressId, LocalDateTime lastUpdate) {
        super(Store.STORE);

        setStoreId(storeId);
        setManagerStaffId(managerStaffId);
        setAddressId(addressId);
        setLastUpdate(lastUpdate);
    }

    /**
     * Create a detached, initialised StoreRecord
     */
    public StoreRecord(com.github.btpka3.first.spring.jooq.domain.tables.pojos.Store value) {
        super(Store.STORE);

        if (value != null) {
            setStoreId(value.getStoreId());
            setManagerStaffId(value.getManagerStaffId());
            setAddressId(value.getAddressId());
            setLastUpdate(value.getLastUpdate());
        }
    }
}
