INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (1, 2, 'zhao6', 'zhao6~~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (2, 2, 'qian7', 'qian7~~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (3, 2, 'sun8',  'sun8~~~~~~~');
