INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (1, 1, 'zhang3', 'zhang3~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (2, 1, 'li4',    'li4~~~~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (3, 1, 'wang5',  'wang5~~~~~~');


INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (4, 3, 'liuDa', 'liuDa~~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (5, 3, 'chen2', 'chen2~~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (6, 3, 'wu9',   'wu9~~~~~~~~');
INSERT INTO T_USER (ID, HOSPITAL_ID, NAME, REMARK) VALUES (7, 3, 'zheng10','zheng10~~~~');
