/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActorInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short  actorId;
    private String firstName;
    private String lastName;
    private String filmInfo;

    public ActorInfo() {}

    public ActorInfo(ActorInfo value) {
        this.actorId = value.actorId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.filmInfo = value.filmInfo;
    }

    public ActorInfo(
        Short  actorId,
        String firstName,
        String lastName,
        String filmInfo
    ) {
        this.actorId = actorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.filmInfo = filmInfo;
    }

    /**
     * Getter for <code>sakila.actor_info.actor_id</code>.
     */
    public Short getActorId() {
        return this.actorId;
    }

    /**
     * Setter for <code>sakila.actor_info.actor_id</code>.
     */
    public ActorInfo setActorId(Short actorId) {
        this.actorId = actorId;
        return this;
    }

    /**
     * Getter for <code>sakila.actor_info.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>sakila.actor_info.first_name</code>.
     */
    public ActorInfo setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>sakila.actor_info.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>sakila.actor_info.last_name</code>.
     */
    public ActorInfo setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>sakila.actor_info.film_info</code>.
     */
    public String getFilmInfo() {
        return this.filmInfo;
    }

    /**
     * Setter for <code>sakila.actor_info.film_info</code>.
     */
    public ActorInfo setFilmInfo(String filmInfo) {
        this.filmInfo = filmInfo;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActorInfo (");

        sb.append(actorId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(filmInfo);

        sb.append(")");
        return sb.toString();
    }
}
