/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Actor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short         actorId;
    private String        firstName;
    private String        lastName;
    private LocalDateTime lastUpdate;

    public Actor() {}

    public Actor(Actor value) {
        this.actorId = value.actorId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.lastUpdate = value.lastUpdate;
    }

    public Actor(
        Short         actorId,
        String        firstName,
        String        lastName,
        LocalDateTime lastUpdate
    ) {
        this.actorId = actorId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.actor.actor_id</code>.
     */
    public Short getActorId() {
        return this.actorId;
    }

    /**
     * Setter for <code>sakila.actor.actor_id</code>.
     */
    public Actor setActorId(Short actorId) {
        this.actorId = actorId;
        return this;
    }

    /**
     * Getter for <code>sakila.actor.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>sakila.actor.first_name</code>.
     */
    public Actor setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>sakila.actor.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>sakila.actor.last_name</code>.
     */
    public Actor setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>sakila.actor.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.actor.last_update</code>.
     */
    public Actor setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Actor (");

        sb.append(actorId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
