/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Country implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short         countryId;
    private String        country;
    private LocalDateTime lastUpdate;

    public Country() {}

    public Country(Country value) {
        this.countryId = value.countryId;
        this.country = value.country;
        this.lastUpdate = value.lastUpdate;
    }

    public Country(
        Short         countryId,
        String        country,
        LocalDateTime lastUpdate
    ) {
        this.countryId = countryId;
        this.country = country;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.country.country_id</code>.
     */
    public Short getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>sakila.country.country_id</code>.
     */
    public Country setCountryId(Short countryId) {
        this.countryId = countryId;
        return this;
    }

    /**
     * Getter for <code>sakila.country.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>sakila.country.country</code>.
     */
    public Country setCountry(String country) {
        this.country = country;
        return this;
    }

    /**
     * Getter for <code>sakila.country.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.country.last_update</code>.
     */
    public Country setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Country (");

        sb.append(countryId);
        sb.append(", ").append(country);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
