/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short         customerId;
    private Byte          storeId;
    private String        firstName;
    private String        lastName;
    private String        email;
    private Short         addressId;
    private Byte          active;
    private LocalDateTime createDate;
    private LocalDateTime lastUpdate;

    public Customer() {}

    public Customer(Customer value) {
        this.customerId = value.customerId;
        this.storeId = value.storeId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.addressId = value.addressId;
        this.active = value.active;
        this.createDate = value.createDate;
        this.lastUpdate = value.lastUpdate;
    }

    public Customer(
        Short         customerId,
        Byte          storeId,
        String        firstName,
        String        lastName,
        String        email,
        Short         addressId,
        Byte          active,
        LocalDateTime createDate,
        LocalDateTime lastUpdate
    ) {
        this.customerId = customerId;
        this.storeId = storeId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.addressId = addressId;
        this.active = active;
        this.createDate = createDate;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.customer.customer_id</code>.
     */
    public Short getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>sakila.customer.customer_id</code>.
     */
    public Customer setCustomerId(Short customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.store_id</code>.
     */
    public Byte getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>sakila.customer.store_id</code>.
     */
    public Customer setStoreId(Byte storeId) {
        this.storeId = storeId;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>sakila.customer.first_name</code>.
     */
    public Customer setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>sakila.customer.last_name</code>.
     */
    public Customer setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>sakila.customer.email</code>.
     */
    public Customer setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.address_id</code>.
     */
    public Short getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>sakila.customer.address_id</code>.
     */
    public Customer setAddressId(Short addressId) {
        this.addressId = addressId;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.active</code>.
     */
    public Byte getActive() {
        return this.active;
    }

    /**
     * Setter for <code>sakila.customer.active</code>.
     */
    public Customer setActive(Byte active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.create_date</code>.
     */
    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    /**
     * Setter for <code>sakila.customer.create_date</code>.
     */
    public Customer setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
        return this;
    }

    /**
     * Getter for <code>sakila.customer.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.customer.last_update</code>.
     */
    public Customer setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(customerId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(addressId);
        sb.append(", ").append(active);
        sb.append(", ").append(createDate);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
