/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import com.github.btpka3.first.spring.jooq.domain.enums.FilmListRating;

import java.io.Serializable;
import java.math.BigDecimal;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmList implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Short          fid;
    private final String         title;
    private final String         description;
    private final String         category;
    private final BigDecimal     price;
    private final Short          length;
    private final FilmListRating rating;
    private final String         actors;

    public FilmList(FilmList value) {
        this.fid = value.fid;
        this.title = value.title;
        this.description = value.description;
        this.category = value.category;
        this.price = value.price;
        this.length = value.length;
        this.rating = value.rating;
        this.actors = value.actors;
    }

    public FilmList(
        Short          fid,
        String         title,
        String         description,
        String         category,
        BigDecimal     price,
        Short          length,
        FilmListRating rating,
        String         actors
    ) {
        this.fid = fid;
        this.title = title;
        this.description = description;
        this.category = category;
        this.price = price;
        this.length = length;
        this.rating = rating;
        this.actors = actors;
    }

    /**
     * Getter for <code>sakila.film_list.FID</code>.
     */
    public Short getFid() {
        return this.fid;
    }

    /**
     * Getter for <code>sakila.film_list.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>sakila.film_list.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Getter for <code>sakila.film_list.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Getter for <code>sakila.film_list.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>sakila.film_list.length</code>.
     */
    public Short getLength() {
        return this.length;
    }

    /**
     * Getter for <code>sakila.film_list.rating</code>.
     */
    public FilmListRating getRating() {
        return this.rating;
    }

    /**
     * Getter for <code>sakila.film_list.actors</code>.
     */
    public String getActors() {
        return this.actors;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmList (");

        sb.append(fid);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(category);
        sb.append(", ").append(price);
        sb.append(", ").append(length);
        sb.append(", ").append(rating);
        sb.append(", ").append(actors);

        sb.append(")");
        return sb.toString();
    }
}
