/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmText implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Short  filmId;
    private final String title;
    private final String description;

    public FilmText(FilmText value) {
        this.filmId = value.filmId;
        this.title = value.title;
        this.description = value.description;
    }

    public FilmText(
        Short  filmId,
        String title,
        String description
    ) {
        this.filmId = filmId;
        this.title = title;
        this.description = description;
    }

    /**
     * Getter for <code>sakila.film_text.film_id</code>.
     */
    public Short getFilmId() {
        return this.filmId;
    }

    /**
     * Getter for <code>sakila.film_text.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>sakila.film_text.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmText (");

        sb.append(filmId);
        sb.append(", ").append(title);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
