/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short         filmId;
    private Byte          categoryId;
    private LocalDateTime lastUpdate;

    public FilmCategory() {}

    public FilmCategory(FilmCategory value) {
        this.filmId = value.filmId;
        this.categoryId = value.categoryId;
        this.lastUpdate = value.lastUpdate;
    }

    public FilmCategory(
        Short         filmId,
        Byte          categoryId,
        LocalDateTime lastUpdate
    ) {
        this.filmId = filmId;
        this.categoryId = categoryId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.film_category.film_id</code>.
     */
    public Short getFilmId() {
        return this.filmId;
    }

    /**
     * Setter for <code>sakila.film_category.film_id</code>.
     */
    public FilmCategory setFilmId(Short filmId) {
        this.filmId = filmId;
        return this;
    }

    /**
     * Getter for <code>sakila.film_category.category_id</code>.
     */
    public Byte getCategoryId() {
        return this.categoryId;
    }

    /**
     * Setter for <code>sakila.film_category.category_id</code>.
     */
    public FilmCategory setCategoryId(Byte categoryId) {
        this.categoryId = categoryId;
        return this;
    }

    /**
     * Getter for <code>sakila.film_category.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.film_category.last_update</code>.
     */
    public FilmCategory setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmCategory (");

        sb.append(filmId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
