/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import com.github.btpka3.first.spring.jooq.domain.enums.FilmListRating;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilmList implements Serializable {

    private static final long serialVersionUID = 1L;

    private Short fid;
    private String title;
    private String description;
    private String category;
    private BigDecimal price;
    private Short length;
    private FilmListRating rating;
    private String actors;

    public FilmList() {}

    public FilmList(FilmList value) {
        this.fid = value.fid;
        this.title = value.title;
        this.description = value.description;
        this.category = value.category;
        this.price = value.price;
        this.length = value.length;
        this.rating = value.rating;
        this.actors = value.actors;
    }

    public FilmList(
        Short fid,
        String title,
        String description,
        String category,
        BigDecimal price,
        Short length,
        FilmListRating rating,
        String actors
    ) {
        this.fid = fid;
        this.title = title;
        this.description = description;
        this.category = category;
        this.price = price;
        this.length = length;
        this.rating = rating;
        this.actors = actors;
    }

    /**
     * Getter for <code>sakila.film_list.FID</code>.
     */
    public Short getFid() {
        return this.fid;
    }

    /**
     * Setter for <code>sakila.film_list.FID</code>.
     */
    public void setFid(Short fid) {
        this.fid = fid;
    }

    /**
     * Getter for <code>sakila.film_list.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>sakila.film_list.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>sakila.film_list.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>sakila.film_list.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>sakila.film_list.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>sakila.film_list.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>sakila.film_list.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>sakila.film_list.price</code>.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>sakila.film_list.length</code>.
     */
    public Short getLength() {
        return this.length;
    }

    /**
     * Setter for <code>sakila.film_list.length</code>.
     */
    public void setLength(Short length) {
        this.length = length;
    }

    /**
     * Getter for <code>sakila.film_list.rating</code>.
     */
    public FilmListRating getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>sakila.film_list.rating</code>.
     */
    public void setRating(FilmListRating rating) {
        this.rating = rating;
    }

    /**
     * Getter for <code>sakila.film_list.actors</code>.
     */
    public String getActors() {
        return this.actors;
    }

    /**
     * Setter for <code>sakila.film_list.actors</code>.
     */
    public void setActors(String actors) {
        this.actors = actors;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FilmList other = (FilmList) obj;
        if (this.fid == null) {
            if (other.fid != null)
                return false;
        }
        else if (!this.fid.equals(other.fid))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.length == null) {
            if (other.length != null)
                return false;
        }
        else if (!this.length.equals(other.length))
            return false;
        if (this.rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!this.rating.equals(other.rating))
            return false;
        if (this.actors == null) {
            if (other.actors != null)
                return false;
        }
        else if (!this.actors.equals(other.actors))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.fid == null) ? 0 : this.fid.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.length == null) ? 0 : this.length.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.actors == null) ? 0 : this.actors.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmList (");

        sb.append(fid);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(category);
        sb.append(", ").append(price);
        sb.append(", ").append(length);
        sb.append(", ").append(rating);
        sb.append(", ").append(actors);

        sb.append(")");
        return sb.toString();
    }
}
