/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmActor implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Short         actorId;
    private final Short         filmId;
    private final LocalDateTime lastUpdate;

    public FilmActor(FilmActor value) {
        this.actorId = value.actorId;
        this.filmId = value.filmId;
        this.lastUpdate = value.lastUpdate;
    }

    public FilmActor(
        Short         actorId,
        Short         filmId,
        LocalDateTime lastUpdate
    ) {
        this.actorId = actorId;
        this.filmId = filmId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.film_actor.actor_id</code>.
     */
    public Short getActorId() {
        return this.actorId;
    }

    /**
     * Getter for <code>sakila.film_actor.film_id</code>.
     */
    public Short getFilmId() {
        return this.filmId;
    }

    /**
     * Getter for <code>sakila.film_actor.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FilmActor (");

        sb.append(actorId);
        sb.append(", ").append(filmId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
