/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Inventory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       inventoryId;
    private Short         filmId;
    private Byte          storeId;
    private LocalDateTime lastUpdate;

    public Inventory() {}

    public Inventory(Inventory value) {
        this.inventoryId = value.inventoryId;
        this.filmId = value.filmId;
        this.storeId = value.storeId;
        this.lastUpdate = value.lastUpdate;
    }

    public Inventory(
        Integer       inventoryId,
        Short         filmId,
        Byte          storeId,
        LocalDateTime lastUpdate
    ) {
        this.inventoryId = inventoryId;
        this.filmId = filmId;
        this.storeId = storeId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.inventory.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return this.inventoryId;
    }

    /**
     * Setter for <code>sakila.inventory.inventory_id</code>.
     */
    public Inventory setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
        return this;
    }

    /**
     * Getter for <code>sakila.inventory.film_id</code>.
     */
    public Short getFilmId() {
        return this.filmId;
    }

    /**
     * Setter for <code>sakila.inventory.film_id</code>.
     */
    public Inventory setFilmId(Short filmId) {
        this.filmId = filmId;
        return this;
    }

    /**
     * Getter for <code>sakila.inventory.store_id</code>.
     */
    public Byte getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>sakila.inventory.store_id</code>.
     */
    public Inventory setStoreId(Byte storeId) {
        this.storeId = storeId;
        return this;
    }

    /**
     * Getter for <code>sakila.inventory.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.inventory.last_update</code>.
     */
    public Inventory setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Inventory (");

        sb.append(inventoryId);
        sb.append(", ").append(filmId);
        sb.append(", ").append(storeId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
