/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Byte          languageId;
    private final String        name;
    private final LocalDateTime lastUpdate;

    public Language(Language value) {
        this.languageId = value.languageId;
        this.name = value.name;
        this.lastUpdate = value.lastUpdate;
    }

    public Language(
        Byte          languageId,
        String        name,
        LocalDateTime lastUpdate
    ) {
        this.languageId = languageId;
        this.name = name;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.language.language_id</code>.
     */
    public Byte getLanguageId() {
        return this.languageId;
    }

    /**
     * Getter for <code>sakila.language.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>sakila.language.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Language (");

        sb.append(languageId);
        sb.append(", ").append(name);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
