/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rental implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer rentalId;
    private LocalDateTime rentalDate;
    private Integer inventoryId;
    private Short customerId;
    private LocalDateTime returnDate;
    private Byte staffId;
    private LocalDateTime lastUpdate;

    public Rental() {}

    public Rental(Rental value) {
        this.rentalId = value.rentalId;
        this.rentalDate = value.rentalDate;
        this.inventoryId = value.inventoryId;
        this.customerId = value.customerId;
        this.returnDate = value.returnDate;
        this.staffId = value.staffId;
        this.lastUpdate = value.lastUpdate;
    }

    public Rental(
        Integer rentalId,
        LocalDateTime rentalDate,
        Integer inventoryId,
        Short customerId,
        LocalDateTime returnDate,
        Byte staffId,
        LocalDateTime lastUpdate
    ) {
        this.rentalId = rentalId;
        this.rentalDate = rentalDate;
        this.inventoryId = inventoryId;
        this.customerId = customerId;
        this.returnDate = returnDate;
        this.staffId = staffId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.rental.rental_id</code>.
     */
    public Integer getRentalId() {
        return this.rentalId;
    }

    /**
     * Setter for <code>sakila.rental.rental_id</code>.
     */
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }

    /**
     * Getter for <code>sakila.rental.rental_date</code>.
     */
    public LocalDateTime getRentalDate() {
        return this.rentalDate;
    }

    /**
     * Setter for <code>sakila.rental.rental_date</code>.
     */
    public void setRentalDate(LocalDateTime rentalDate) {
        this.rentalDate = rentalDate;
    }

    /**
     * Getter for <code>sakila.rental.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return this.inventoryId;
    }

    /**
     * Setter for <code>sakila.rental.inventory_id</code>.
     */
    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * Getter for <code>sakila.rental.customer_id</code>.
     */
    public Short getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>sakila.rental.customer_id</code>.
     */
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>sakila.rental.return_date</code>.
     */
    public LocalDateTime getReturnDate() {
        return this.returnDate;
    }

    /**
     * Setter for <code>sakila.rental.return_date</code>.
     */
    public void setReturnDate(LocalDateTime returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * Getter for <code>sakila.rental.staff_id</code>.
     */
    public Byte getStaffId() {
        return this.staffId;
    }

    /**
     * Setter for <code>sakila.rental.staff_id</code>.
     */
    public void setStaffId(Byte staffId) {
        this.staffId = staffId;
    }

    /**
     * Getter for <code>sakila.rental.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.rental.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Rental other = (Rental) obj;
        if (this.rentalId == null) {
            if (other.rentalId != null)
                return false;
        }
        else if (!this.rentalId.equals(other.rentalId))
            return false;
        if (this.rentalDate == null) {
            if (other.rentalDate != null)
                return false;
        }
        else if (!this.rentalDate.equals(other.rentalDate))
            return false;
        if (this.inventoryId == null) {
            if (other.inventoryId != null)
                return false;
        }
        else if (!this.inventoryId.equals(other.inventoryId))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.returnDate == null) {
            if (other.returnDate != null)
                return false;
        }
        else if (!this.returnDate.equals(other.returnDate))
            return false;
        if (this.staffId == null) {
            if (other.staffId != null)
                return false;
        }
        else if (!this.staffId.equals(other.staffId))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.rentalId == null) ? 0 : this.rentalId.hashCode());
        result = prime * result + ((this.rentalDate == null) ? 0 : this.rentalDate.hashCode());
        result = prime * result + ((this.inventoryId == null) ? 0 : this.inventoryId.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.returnDate == null) ? 0 : this.returnDate.hashCode());
        result = prime * result + ((this.staffId == null) ? 0 : this.staffId.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rental (");

        sb.append(rentalId);
        sb.append(", ").append(rentalDate);
        sb.append(", ").append(inventoryId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(returnDate);
        sb.append(", ").append(staffId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
