/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rental implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       rentalId;
    private LocalDateTime rentalDate;
    private Integer       inventoryId;
    private Short         customerId;
    private LocalDateTime returnDate;
    private Byte          staffId;
    private LocalDateTime lastUpdate;

    public Rental() {}

    public Rental(Rental value) {
        this.rentalId = value.rentalId;
        this.rentalDate = value.rentalDate;
        this.inventoryId = value.inventoryId;
        this.customerId = value.customerId;
        this.returnDate = value.returnDate;
        this.staffId = value.staffId;
        this.lastUpdate = value.lastUpdate;
    }

    public Rental(
        Integer       rentalId,
        LocalDateTime rentalDate,
        Integer       inventoryId,
        Short         customerId,
        LocalDateTime returnDate,
        Byte          staffId,
        LocalDateTime lastUpdate
    ) {
        this.rentalId = rentalId;
        this.rentalDate = rentalDate;
        this.inventoryId = inventoryId;
        this.customerId = customerId;
        this.returnDate = returnDate;
        this.staffId = staffId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.rental.rental_id</code>.
     */
    public Integer getRentalId() {
        return this.rentalId;
    }

    /**
     * Setter for <code>sakila.rental.rental_id</code>.
     */
    public Rental setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
        return this;
    }

    /**
     * Getter for <code>sakila.rental.rental_date</code>.
     */
    public LocalDateTime getRentalDate() {
        return this.rentalDate;
    }

    /**
     * Setter for <code>sakila.rental.rental_date</code>.
     */
    public Rental setRentalDate(LocalDateTime rentalDate) {
        this.rentalDate = rentalDate;
        return this;
    }

    /**
     * Getter for <code>sakila.rental.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return this.inventoryId;
    }

    /**
     * Setter for <code>sakila.rental.inventory_id</code>.
     */
    public Rental setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
        return this;
    }

    /**
     * Getter for <code>sakila.rental.customer_id</code>.
     */
    public Short getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>sakila.rental.customer_id</code>.
     */
    public Rental setCustomerId(Short customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Getter for <code>sakila.rental.return_date</code>.
     */
    public LocalDateTime getReturnDate() {
        return this.returnDate;
    }

    /**
     * Setter for <code>sakila.rental.return_date</code>.
     */
    public Rental setReturnDate(LocalDateTime returnDate) {
        this.returnDate = returnDate;
        return this;
    }

    /**
     * Getter for <code>sakila.rental.staff_id</code>.
     */
    public Byte getStaffId() {
        return this.staffId;
    }

    /**
     * Setter for <code>sakila.rental.staff_id</code>.
     */
    public Rental setStaffId(Byte staffId) {
        this.staffId = staffId;
        return this;
    }

    /**
     * Getter for <code>sakila.rental.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.rental.last_update</code>.
     */
    public Rental setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Rental (");

        sb.append(rentalId);
        sb.append(", ").append(rentalDate);
        sb.append(", ").append(inventoryId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(returnDate);
        sb.append(", ").append(staffId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
