/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesByStore implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String     store;
    private final String     manager;
    private final BigDecimal totalSales;

    public SalesByStore(SalesByStore value) {
        this.store = value.store;
        this.manager = value.manager;
        this.totalSales = value.totalSales;
    }

    public SalesByStore(
        String     store,
        String     manager,
        BigDecimal totalSales
    ) {
        this.store = store;
        this.manager = manager;
        this.totalSales = totalSales;
    }

    /**
     * Getter for <code>sakila.sales_by_store.store</code>.
     */
    public String getStore() {
        return this.store;
    }

    /**
     * Getter for <code>sakila.sales_by_store.manager</code>.
     */
    public String getManager() {
        return this.manager;
    }

    /**
     * Getter for <code>sakila.sales_by_store.total_sales</code>.
     */
    public BigDecimal getTotalSales() {
        return this.totalSales;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SalesByStore (");

        sb.append(store);
        sb.append(", ").append(manager);
        sb.append(", ").append(totalSales);

        sb.append(")");
        return sb.toString();
    }
}
