/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffList implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Byte   id;
    private final String name;
    private final String address;
    private final String zipCode;
    private final String phone;
    private final String city;
    private final String country;
    private final Byte   sid;

    public StaffList(StaffList value) {
        this.id = value.id;
        this.name = value.name;
        this.address = value.address;
        this.zipCode = value.zipCode;
        this.phone = value.phone;
        this.city = value.city;
        this.country = value.country;
        this.sid = value.sid;
    }

    public StaffList(
        Byte   id,
        String name,
        String address,
        String zipCode,
        String phone,
        String city,
        String country,
        Byte   sid
    ) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.zipCode = zipCode;
        this.phone = phone;
        this.city = city;
        this.country = country;
        this.sid = sid;
    }

    /**
     * Getter for <code>sakila.staff_list.ID</code>.
     */
    public Byte getId() {
        return this.id;
    }

    /**
     * Getter for <code>sakila.staff_list.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>sakila.staff_list.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Getter for <code>sakila.staff_list.zip code</code>.
     */
    public String getZipCode() {
        return this.zipCode;
    }

    /**
     * Getter for <code>sakila.staff_list.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Getter for <code>sakila.staff_list.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Getter for <code>sakila.staff_list.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Getter for <code>sakila.staff_list.SID</code>.
     */
    public Byte getSid() {
        return this.sid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StaffList (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(address);
        sb.append(", ").append(zipCode);
        sb.append(", ").append(phone);
        sb.append(", ").append(city);
        sb.append(", ").append(country);
        sb.append(", ").append(sid);

        sb.append(")");
        return sb.toString();
    }
}
