/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Byte          staffId;
    private final String        firstName;
    private final String        lastName;
    private final Short         addressId;
    private final byte[]        picture;
    private final String        email;
    private final Byte          storeId;
    private final Byte          active;
    private final String        username;
    private final String        password;
    private final LocalDateTime lastUpdate;

    public Staff(Staff value) {
        this.staffId = value.staffId;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.addressId = value.addressId;
        this.picture = value.picture;
        this.email = value.email;
        this.storeId = value.storeId;
        this.active = value.active;
        this.username = value.username;
        this.password = value.password;
        this.lastUpdate = value.lastUpdate;
    }

    public Staff(
        Byte          staffId,
        String        firstName,
        String        lastName,
        Short         addressId,
        byte[]        picture,
        String        email,
        Byte          storeId,
        Byte          active,
        String        username,
        String        password,
        LocalDateTime lastUpdate
    ) {
        this.staffId = staffId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.addressId = addressId;
        this.picture = picture;
        this.email = email;
        this.storeId = storeId;
        this.active = active;
        this.username = username;
        this.password = password;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.staff.staff_id</code>.
     */
    public Byte getStaffId() {
        return this.staffId;
    }

    /**
     * Getter for <code>sakila.staff.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Getter for <code>sakila.staff.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Getter for <code>sakila.staff.address_id</code>.
     */
    public Short getAddressId() {
        return this.addressId;
    }

    /**
     * Getter for <code>sakila.staff.picture</code>.
     */
    public byte[] getPicture() {
        return this.picture;
    }

    /**
     * Getter for <code>sakila.staff.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>sakila.staff.store_id</code>.
     */
    public Byte getStoreId() {
        return this.storeId;
    }

    /**
     * Getter for <code>sakila.staff.active</code>.
     */
    public Byte getActive() {
        return this.active;
    }

    /**
     * Getter for <code>sakila.staff.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Getter for <code>sakila.staff.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Getter for <code>sakila.staff.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Staff (");

        sb.append(staffId);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(addressId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(email);
        sb.append(", ").append(storeId);
        sb.append(", ").append(active);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
