/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.20.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    private Byte storeId;
    private Byte managerStaffId;
    private Short addressId;
    private LocalDateTime lastUpdate;

    public Store() {}

    public Store(Store value) {
        this.storeId = value.storeId;
        this.managerStaffId = value.managerStaffId;
        this.addressId = value.addressId;
        this.lastUpdate = value.lastUpdate;
    }

    public Store(
        Byte storeId,
        Byte managerStaffId,
        Short addressId,
        LocalDateTime lastUpdate
    ) {
        this.storeId = storeId;
        this.managerStaffId = managerStaffId;
        this.addressId = addressId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.store.store_id</code>.
     */
    public Byte getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>sakila.store.store_id</code>.
     */
    public void setStoreId(Byte storeId) {
        this.storeId = storeId;
    }

    /**
     * Getter for <code>sakila.store.manager_staff_id</code>.
     */
    public Byte getManagerStaffId() {
        return this.managerStaffId;
    }

    /**
     * Setter for <code>sakila.store.manager_staff_id</code>.
     */
    public void setManagerStaffId(Byte managerStaffId) {
        this.managerStaffId = managerStaffId;
    }

    /**
     * Getter for <code>sakila.store.address_id</code>.
     */
    public Short getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>sakila.store.address_id</code>.
     */
    public void setAddressId(Short addressId) {
        this.addressId = addressId;
    }

    /**
     * Getter for <code>sakila.store.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.store.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Store other = (Store) obj;
        if (this.storeId == null) {
            if (other.storeId != null)
                return false;
        }
        else if (!this.storeId.equals(other.storeId))
            return false;
        if (this.managerStaffId == null) {
            if (other.managerStaffId != null)
                return false;
        }
        else if (!this.managerStaffId.equals(other.managerStaffId))
            return false;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.lastUpdate == null) {
            if (other.lastUpdate != null)
                return false;
        }
        else if (!this.lastUpdate.equals(other.lastUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.storeId == null) ? 0 : this.storeId.hashCode());
        result = prime * result + ((this.managerStaffId == null) ? 0 : this.managerStaffId.hashCode());
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.lastUpdate == null) ? 0 : this.lastUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(storeId);
        sb.append(", ").append(managerStaffId);
        sb.append(", ").append(addressId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
