/*
 * This file is generated by jOOQ.
 */
package com.github.btpka3.first.spring.jooq.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    private Byte          storeId;
    private Byte          managerStaffId;
    private Short         addressId;
    private LocalDateTime lastUpdate;

    public Store() {}

    public Store(Store value) {
        this.storeId = value.storeId;
        this.managerStaffId = value.managerStaffId;
        this.addressId = value.addressId;
        this.lastUpdate = value.lastUpdate;
    }

    public Store(
        Byte          storeId,
        Byte          managerStaffId,
        Short         addressId,
        LocalDateTime lastUpdate
    ) {
        this.storeId = storeId;
        this.managerStaffId = managerStaffId;
        this.addressId = addressId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>sakila.store.store_id</code>.
     */
    public Byte getStoreId() {
        return this.storeId;
    }

    /**
     * Setter for <code>sakila.store.store_id</code>.
     */
    public Store setStoreId(Byte storeId) {
        this.storeId = storeId;
        return this;
    }

    /**
     * Getter for <code>sakila.store.manager_staff_id</code>.
     */
    public Byte getManagerStaffId() {
        return this.managerStaffId;
    }

    /**
     * Setter for <code>sakila.store.manager_staff_id</code>.
     */
    public Store setManagerStaffId(Byte managerStaffId) {
        this.managerStaffId = managerStaffId;
        return this;
    }

    /**
     * Getter for <code>sakila.store.address_id</code>.
     */
    public Short getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>sakila.store.address_id</code>.
     */
    public Store setAddressId(Short addressId) {
        this.addressId = addressId;
        return this;
    }

    /**
     * Getter for <code>sakila.store.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>sakila.store.last_update</code>.
     */
    public Store setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Store (");

        sb.append(storeId);
        sb.append(", ").append(managerStaffId);
        sb.append(", ").append(addressId);
        sb.append(", ").append(lastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
